# Generated by Django 5.2.17 on 2026-08-12 06:53

import apps.bookings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_address'),
        ('catalog', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.bookings.models.generate_reference, editable=False, help_text='Short human-readable id, quoted in support conversations.', max_length=12, unique=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'Provider on the way'), ('IN_PROGRESS', 'In progress'), ('AWAITING_CONFIRMATION', 'Awaiting customer confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=24)),
                ('spec_key', models.CharField(editable=False, max_length=60)),
                ('details', models.JSONField(default=dict)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Null for an on-demand request.', null=True)),
                ('address_label', models.CharField(blank=True, max_length=10)),
                ('address_street', models.CharField(max_length=255)),
                ('address_landmark', models.CharField(max_length=255)),
                ('address_area', models.CharField(blank=True, max_length=120)),
                ('address_lga', models.CharField(blank=True, max_length=120)),
                ('address_state', models.CharField(choices=[('ABIA', 'Abia'), ('ADAMAWA', 'Adamawa'), ('AKWA_IBOM', 'Akwa Ibom'), ('ANAMBRA', 'Anambra'), ('BAUCHI', 'Bauchi'), ('BAYELSA', 'Bayelsa'), ('BENUE', 'Benue'), ('BORNO', 'Borno'), ('CROSS_RIVER', 'Cross River'), ('DELTA', 'Delta'), ('EBONYI', 'Ebonyi'), ('EDO', 'Edo'), ('EKITI', 'Ekiti'), ('ENUGU', 'Enugu'), ('FCT', 'Federal Capital Territory'), ('GOMBE', 'Gombe'), ('IMO', 'Imo'), ('JIGAWA', 'Jigawa'), ('KADUNA', 'Kaduna'), ('KANO', 'Kano'), ('KATSINA', 'Katsina'), ('KEBBI', 'Kebbi'), ('KOGI', 'Kogi'), ('KWARA', 'Kwara'), ('LAGOS', 'Lagos'), ('NASARAWA', 'Nasarawa'), ('NIGER', 'Niger'), ('OGUN', 'Ogun'), ('ONDO', 'Ondo'), ('OSUN', 'Osun'), ('OYO', 'Oyo'), ('PLATEAU', 'Plateau'), ('RIVERS', 'Rivers'), ('SOKOTO', 'Sokoto'), ('TARABA', 'Taraba'), ('YOBE', 'Yobe'), ('ZAMFARA', 'Zamfara')], max_length=20)),
                ('address_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_directions', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='providers.providerprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.service')),
                ('source_address', models.ForeignKey(blank=True, help_text='The saved address this was copied from, if it still exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.address')),
            ],
            options={
                'db_table': 'bookings_booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'Provider on the way'), ('IN_PROGRESS', 'In progress'), ('AWAITING_CONFIRMATION', 'Awaiting customer confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=24)),
                ('to_status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'Provider on the way'), ('IN_PROGRESS', 'In progress'), ('AWAITING_CONFIRMATION', 'Awaiting customer confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=24)),
                ('actor_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('PROVIDER', 'Provider'), ('SYSTEM', 'System'), ('ADMIN', 'Admin')], max_length=10)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bookings.booking')),
            ],
            options={
                'db_table': 'bookings_status_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', '-created_at'], name='bookings_bo_custome_10bd54_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider', '-created_at'], name='bookings_bo_provide_7ad8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('address_landmark', ''), _negated=True), name='bookings_booking_landmark_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('address_street', ''), _negated=True), name='bookings_booking_street_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('address_latitude__isnull', True), ('address_longitude__isnull', True)), models.Q(('address_latitude__isnull', False), ('address_longitude__isnull', False)), _connector='OR'), name='bookings_booking_coordinates_paired'),
        ),
        migrations.AddIndex(
            model_name='bookingstatusevent',
            index=models.Index(fields=['booking', 'created_at'], name='bookings_st_booking_2d0012_idx'),
        ),
    ]
