# Generated by Django 5.2.17 on 2026-08-12 09:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('MATCHING', 'Finding a provider'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'Provider on the way'), ('IN_PROGRESS', 'In progress'), ('AWAITING_CONFIRMATION', 'Awaiting customer confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'No provider took it')], default='ASSIGNED', max_length=24),
        ),
        migrations.AlterField(
            model_name='bookingstatusevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('MATCHING', 'Finding a provider'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'Provider on the way'), ('IN_PROGRESS', 'In progress'), ('AWAITING_CONFIRMATION', 'Awaiting customer confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'No provider took it')], max_length=24),
        ),
        migrations.AlterField(
            model_name='bookingstatusevent',
            name='to_status',
            field=models.CharField(choices=[('MATCHING', 'Finding a provider'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'Provider on the way'), ('IN_PROGRESS', 'In progress'), ('AWAITING_CONFIRMATION', 'Awaiting customer confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'No provider took it')], max_length=24),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('DIRECT', 'Requested directly by the customer'), ('BROADCAST', 'Offered to eligible providers')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting a response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Lapsed'), ('SUPERSEDED', 'Another provider took it')], default='PENDING', max_length=12)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='bookings.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='providers.providerprofile')),
            ],
            options={
                'db_table': 'bookings_offer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status', '-created_at'], name='bookings_of_provide_1f52aa_idx'), models.Index(fields=['booking', 'status'], name='bookings_of_booking_928356_idx'), models.Index(fields=['status', 'expires_at'], name='bookings_of_status_3cffea_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'provider'), name='bookings_offer_unique_per_provider'), models.UniqueConstraint(condition=models.Q(('status', 'ACCEPTED')), fields=('booking',), name='bookings_offer_one_accepted_per_booking'), models.CheckConstraint(condition=models.Q(models.Q(('responded_at__isnull', True), ('status', 'PENDING')), models.Q(models.Q(('status', 'PENDING'), _negated=True), ('responded_at__isnull', False)), _connector='OR'), name='bookings_offer_responded_at_matches_status')],
            },
        ),
    ]
