# Generated by Django 5.2.17 on 2026-08-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('MATCHING', 'Finding a provider'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'Provider on the way'), ('IN_PROGRESS', 'In progress'), ('AWAITING_CONFIRMATION', 'Awaiting customer confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'No provider took it')], default='MATCHING', max_length=24),
        ),
    ]
