# Generated by Django 5.2.17 on 2026-08-14 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_verificationchallenge'),
        ('bookings', '0003_alter_booking_status'),
        ('catalog', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_kobo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_kobo__gte', 0)), name='bookings_booking_total_not_negative'),
        ),
    ]
