# Generated by Django 5.2.17 on 2026-08-15 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('BOOKING_CREATED', 'Booking created'), ('PROVIDER_ASSIGNED', 'A provider took the job'), ('BOOKING_EN_ROUTE', 'Provider on the way'), ('BOOKING_IN_PROGRESS', 'Work started'), ('BOOKING_AWAITING_CONFIRMATION', 'Work finished, awaiting confirmation'), ('BOOKING_COMPLETED', 'Booking completed'), ('PAYMENT_SUCCEEDED', 'Payment received'), ('PAYMENT_FAILED', 'Payment did not go through'), ('OFFER_RECEIVED', 'New job offered'), ('OFFER_EXPIRED', 'Offer window closed'), ('OFFER_ACCEPTED', 'You took the job'), ('OFFER_SUPERSEDED', 'Somebody else took it'), ('JOB_CANCELLED', 'A job was cancelled'), ('EARNINGS_AVAILABLE', 'Earnings available'), ('PAYOUT_REQUESTED', 'Payout requested'), ('PAYOUT_PROCESSING', 'Payout on its way'), ('PAYOUT_PAID', 'Payout paid'), ('PAYOUT_FAILED', 'Payout failed')], max_length=40)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=10)),
                ('subject_type', models.CharField(max_length=40)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('subject_reference', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting to be sent'), ('SENT', 'Handed to the provider'), ('FAILED', 'Could not be delivered'), ('SKIPPED', 'No verified destination for this channel')], default='PENDING', max_length=10)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['status', '-created_at'], name='notificatio_status_37b3f3_idx'), models.Index(fields=['event_type', '-created_at'], name='notificatio_event_t_bb6b48_idx'), models.Index(fields=['subject_id'], name='notificatio_subject_4b3203_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('delivered_at__isnull', False), ('status', 'SENT')), models.Q(models.Q(('status', 'SENT'), _negated=True), ('delivered_at__isnull', True)), _connector='OR'), name='notifications_delivered_at_matches_status'), models.CheckConstraint(condition=models.Q(('status', 'FAILED'), ('status', 'SKIPPED'), ('failure_reason', ''), _connector='OR'), name='notifications_reason_only_when_unsent')],
            },
        ),
    ]
