# Generated by Django 5.2.17 on 2026-08-11 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(help_text="Shown to customers. May differ from the account holder's legal name.", max_length=140)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('provider_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business')], default='INDIVIDUAL', max_length=12)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending submission'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('is_accepting_jobs', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'providers_profile',
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_override_kobo', models.BigIntegerField(blank=True, null=True)),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_services', to='providers.providerprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offered_by', to='catalog.service')),
            ],
            options={
                'db_table': 'providers_service',
                'ordering': ['service__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProviderServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('ABIA', 'Abia'), ('ADAMAWA', 'Adamawa'), ('AKWA_IBOM', 'Akwa Ibom'), ('ANAMBRA', 'Anambra'), ('BAUCHI', 'Bauchi'), ('BAYELSA', 'Bayelsa'), ('BENUE', 'Benue'), ('BORNO', 'Borno'), ('CROSS_RIVER', 'Cross River'), ('DELTA', 'Delta'), ('EBONYI', 'Ebonyi'), ('EDO', 'Edo'), ('EKITI', 'Ekiti'), ('ENUGU', 'Enugu'), ('FCT', 'Federal Capital Territory'), ('GOMBE', 'Gombe'), ('IMO', 'Imo'), ('JIGAWA', 'Jigawa'), ('KADUNA', 'Kaduna'), ('KANO', 'Kano'), ('KATSINA', 'Katsina'), ('KEBBI', 'Kebbi'), ('KOGI', 'Kogi'), ('KWARA', 'Kwara'), ('LAGOS', 'Lagos'), ('NASARAWA', 'Nasarawa'), ('NIGER', 'Niger'), ('OGUN', 'Ogun'), ('ONDO', 'Ondo'), ('OSUN', 'Osun'), ('OYO', 'Oyo'), ('PLATEAU', 'Plateau'), ('RIVERS', 'Rivers'), ('SOKOTO', 'Sokoto'), ('TARABA', 'Taraba'), ('YOBE', 'Yobe'), ('ZAMFARA', 'Zamfara')], max_length=20)),
                ('lga', models.CharField(blank=True, help_text='Blank means the whole state.', max_length=120)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='providers.providerprofile')),
            ],
            options={
                'db_table': 'providers_service_area',
                'ordering': ['state', 'lga'],
            },
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['verification_status'], name='providers_p_verific_7b8f28_idx'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['verification_status', 'is_accepting_jobs'], name='providers_p_verific_6459fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('display_name', ''), _negated=True), name='providers_profile_display_name_not_empty'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['service', 'is_active'], name='providers_s_service_8871ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerservice',
            constraint=models.UniqueConstraint(fields=('provider', 'service'), name='providers_service_unique_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='providerservice',
            constraint=models.CheckConstraint(condition=models.Q(('price_override_kobo__isnull', True), ('price_override_kobo__gte', 0), _connector='OR'), name='providers_service_price_not_negative'),
        ),
        migrations.AddIndex(
            model_name='providerservicearea',
            index=models.Index(fields=['state', 'lga'], name='providers_s_state_6ff2a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerservicearea',
            constraint=models.UniqueConstraint(fields=('provider', 'state', 'lga'), name='providers_area_unique_per_provider'),
        ),
    ]
