# Generated by Django 5.2.17 on 2026-08-26 10:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Started, not yet checked'), ('CHECKING', 'Waiting on the identity provider'), ('CHECK_FAILED', 'The identity check did not pass'), ('UNDER_REVIEW', 'Passed checks, waiting for a reviewer'), ('APPROVED', 'Approved by a reviewer'), ('REJECTED', 'Rejected by a reviewer')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('identity_check_status', models.CharField(choices=[('PENDING', 'Not yet run'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('UNAVAILABLE', 'Could not be checked')], default='PENDING', max_length=12)),
                ('face_match_status', models.CharField(choices=[('PENDING', 'Not yet run'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('UNAVAILABLE', 'Could not be checked')], default='PENDING', max_length=12)),
                ('liveness_status', models.CharField(choices=[('PENDING', 'Not yet run'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('UNAVAILABLE', 'Could not be checked')], default='PENDING', max_length=12)),
                ('identity_vendor', models.CharField(blank=True, max_length=40)),
                ('identity_reference', models.CharField(blank=True, max_length=120)),
                ('identity_method', models.CharField(blank=True, choices=[('NIN_AUTH', 'Nin Auth'), ('NIN_LOOKUP', 'Nin Lookup'), ('BVN_LOOKUP', 'Bvn Lookup')], max_length=20)),
                ('identity_checked_at', models.DateTimeField(blank=True, null=True)),
                ('masked_identifier', models.CharField(blank=True, max_length=4, validators=[django.core.validators.MaxLengthValidator(4)])),
                ('rejection_code', models.CharField(blank=True, choices=[('IDENTITY_NOT_FOUND', 'Identity Not Found'), ('IDENTITY_MISMATCH', 'Identity Mismatch'), ('FACE_MISMATCH', 'Face Mismatch'), ('LIVENESS_FAILED', 'Liveness Failed'), ('CONSENT_DECLINED', 'Consent Declined'), ('AUTHORIZATION_EXPIRED', 'Authorization Expired'), ('IDENTITY_ALREADY_USED', 'Identity Already Used'), ('VENDOR_UNAVAILABLE', 'Vendor Unavailable')], max_length=40)),
                ('audit', models.JSONField(blank=True, default=dict)),
                ('consent_notice_version', models.CharField(blank=True, max_length=20)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, max_length=1000)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_attempts', to='providers.providerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_verifications_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'providers_verification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', '-created_at'], name='providers_v_provide_a29af4_idx'), models.Index(fields=['status'], name='providers_v_status_d466fa_idx'), models.Index(fields=['identity_reference'], name='providers_v_identit_b283cd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('masked_identifier', ''), ('masked_identifier__regex', '^.{1,4}$'), _connector='OR'), name='providers_verification_masked_identifier_is_short'), models.UniqueConstraint(condition=models.Q(('status__in', ('DRAFT', 'CHECKING', 'CHECK_FAILED', 'UNDER_REVIEW'))), fields=('provider',), name='providers_verification_one_open_attempt')],
            },
        ),
    ]
