# Generated by Django 5.2.17 on 2026-08-11 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon_key', models.CharField(blank=True, help_text='Names an icon the app ships. Not a URL, so the app stays offline-capable.', max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'db_table': 'catalog_service_category',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='catalog_ser_is_acti_160864_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('summary', models.CharField(blank=True, help_text='One line, shown in lists.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('spec_key', models.CharField(max_length=60)),
                ('booking_modes', models.CharField(choices=[('ON_DEMAND', 'On demand'), ('SCHEDULED', 'Scheduled'), ('BOTH', 'On demand or scheduled')], default='SCHEDULED', max_length=20)),
                ('pricing_model', models.CharField(choices=[('FIXED', 'Fixed price'), ('PER_HOUR', 'Per hour'), ('PER_ITEM', 'Per item'), ('DISTANCE', 'By distance'), ('QUOTE_ON_SITE', 'Quoted after inspection')], default='FIXED', max_length=20)),
                ('base_price_kobo', models.BigIntegerField(default=0)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.servicecategory')),
            ],
            options={
                'db_table': 'catalog_service',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=140)),
                ('kind', models.CharField(choices=[('BOOLEAN', 'Yes or no'), ('QUANTITY', 'Quantity'), ('CHOICE', 'One of several')], default='BOOLEAN', max_length=10)),
                ('price_delta_kobo', models.BigIntegerField(default=0)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.service')),
            ],
            options={
                'db_table': 'catalog_service_option',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'sort_order'], name='catalog_ser_is_acti_bdabfa_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='catalog_ser_categor_657b62_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('base_price_kobo__gte', 0)), name='catalog_service_base_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='serviceoption',
            constraint=models.UniqueConstraint(fields=('service', 'key'), name='catalog_option_unique_key_per_service'),
        ),
    ]
