# Generated by Django 5.2.17 on 2026-08-12 07:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email')], max_length=10)),
                ('destination', models.CharField(help_text='The normalised address or number this code was sent to.', max_length=254)),
                ('code_hash', models.CharField(editable=False, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_verification_challenge',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'channel', '-created_at'], name='accounts_ve_user_id_50c742_idx'), models.Index(fields=['destination', '-created_at'], name='accounts_ve_destina_ab3906_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('destination', ''), _negated=True), name='accounts_challenge_destination_not_empty'), models.CheckConstraint(condition=models.Q(('max_attempts__gt', 0)), name='accounts_challenge_max_attempts_positive')],
            },
        ),
    ]
