# Generated by Django 5.2.17 on 2026-08-14 07:59

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_booking_total_kobo_and_more'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount_kobo', models.BigIntegerField(help_text='The booking total the customer agreed to, copied at completion.')),
                ('commission_amount_kobo', models.BigIntegerField(help_text="The platform's share, in kobo.")),
                ('provider_amount_kobo', models.BigIntegerField(help_text="The provider's share, in kobo.")),
                ('commission_rate_bps', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian naira')], default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('PAYABLE', 'Owed to the provider')], default='PAYABLE', max_length=12)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='bookings.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='providers.providerprofile')),
            ],
            options={
                'db_table': 'payments_booking_settlement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', '-created_at'], name='payments_bo_provide_4b7357_idx'), models.Index(fields=['provider', 'status'], name='payments_bo_provide_dd240c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('provider_amount_kobo', django.db.models.expressions.CombinedExpression(models.F('gross_amount_kobo'), '-', models.F('commission_amount_kobo')))), name='payments_settlement_amounts_balance'), models.CheckConstraint(condition=models.Q(('gross_amount_kobo__gte', 0)), name='payments_settlement_gross_not_negative'), models.CheckConstraint(condition=models.Q(('commission_amount_kobo__gte', 0)), name='payments_settlement_commission_not_negative'), models.CheckConstraint(condition=models.Q(('provider_amount_kobo__gte', 0)), name='payments_settlement_provider_amount_not_negative'), models.CheckConstraint(condition=models.Q(('commission_amount_kobo__lte', models.F('gross_amount_kobo'))), name='payments_settlement_commission_within_gross'), models.CheckConstraint(condition=models.Q(('commission_rate_bps__lte', 10000)), name='payments_settlement_rate_within_range')],
            },
        ),
        migrations.CreateModel(
            name='PayoutDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_name', models.CharField(max_length=140)),
                ('account_number_last4', models.CharField(max_length=4)),
                ('account_number_hash', models.CharField(max_length=255)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_destination', to='providers.providerprofile')),
            ],
            options={
                'db_table': 'payments_payout_destination',
                'constraints': [models.CheckConstraint(condition=models.Q(('bank_code', ''), _negated=True), name='payments_destination_bank_code_not_empty'), models.CheckConstraint(condition=models.Q(('account_number_hash', ''), _negated=True), name='payments_destination_account_hash_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_kobo', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian naira')], default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROCESSING', 'Being processed'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled by the provider')], default='REQUESTED', max_length=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='providers.providerprofile')),
            ],
            options={
                'db_table': 'payments_payout_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', '-created_at'], name='payments_pa_provide_09b538_idx'), models.Index(fields=['provider', 'status'], name='payments_pa_provide_a6ca74_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_kobo__gt', 0)), name='payments_payout_amount_positive'), models.UniqueConstraint(condition=models.Q(('status__in', ['REQUESTED', 'PROCESSING'])), fields=('provider',), name='payments_payout_one_in_flight_per_provider'), models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('provider', 'idempotency_key'), name='payments_payout_unique_idempotency_key'), models.CheckConstraint(condition=models.Q(models.Q(('processed_at__isnull', False), ('status__in', ['PAID', 'FAILED', 'CANCELLED'])), models.Q(('processed_at__isnull', True), ('status__in', ['REQUESTED', 'PROCESSING'])), _connector='OR'), name='payments_payout_processed_at_matches_status'), models.CheckConstraint(condition=models.Q(('status', 'FAILED'), ('failure_reason', ''), _connector='OR'), name='payments_payout_reason_only_when_failed')],
            },
        ),
    ]
