# Generated by Django 5.2.17 on 2026-08-14 16:30

import apps.payments.intents
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_total_kobo_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutdestination',
            name='resolved_account_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='payoutdestination',
            name='verification_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payoutdestination',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Not yet checked with the bank'), ('VERIFIED', 'Confirmed with the bank'), ('FAILED', 'The bank did not recognise it')], default='UNVERIFIED', max_length=12),
        ),
        migrations.AddField(
            model_name='payoutdestination',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=80)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('amount_kobo', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('payload_digest', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'payments_webhook_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gateway', '-created_at'], name='payments_we_gateway_290ef4_idx'), models.Index(fields=['reference'], name='payments_we_referen_799de7_idx')],
                'constraints': [models.UniqueConstraint(fields=('gateway', 'event_id'), name='payments_webhook_unique_event')],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.payments.intents.generate_reference, editable=False, help_text='Our handle on this payment, and what the provider is told to call it.', max_length=20, unique=True)),
                ('amount_kobo', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian naira')], default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('INITIALIZED', 'Waiting for the customer to pay'), ('SUCCESSFUL', 'Paid'), ('FAILED', 'Not paid')], default='INITIALIZED', max_length=12)),
                ('gateway', models.CharField(max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=120)),
                ('gateway_status', models.CharField(blank=True, max_length=40)),
                ('method', models.CharField(blank=True, max_length=40)),
                ('authorization_url', models.URLField(blank=True, max_length=500)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_payment_intent',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='payments_pa_booking_e87985_idx'), models.Index(fields=['customer', '-created_at'], name='payments_pa_custome_e94435_idx'), models.Index(fields=['status', '-created_at'], name='payments_pa_status_b2f352_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_kobo__gt', 0)), name='payments_intent_amount_positive'), models.UniqueConstraint(condition=models.Q(('status', 'SUCCESSFUL')), fields=('booking',), name='payments_intent_one_successful_per_booking'), models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('booking', 'idempotency_key'), name='payments_intent_unique_idempotency_key'), models.UniqueConstraint(condition=models.Q(('gateway_reference', ''), _negated=True), fields=('gateway', 'gateway_reference'), name='payments_intent_unique_gateway_reference'), models.CheckConstraint(condition=models.Q(models.Q(('paid_at__isnull', False), ('status', 'SUCCESSFUL')), models.Q(('failed_at__isnull', False), ('status', 'FAILED')), models.Q(('failed_at__isnull', True), ('paid_at__isnull', True), ('status', 'INITIALIZED')), _connector='OR'), name='payments_intent_timestamps_match_status')],
            },
        ),
    ]
