# Generated by Django 5.2.17 on 2026-08-14 20:15

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payoutdestination_resolved_account_name_and_more'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('UNSETTLED_PAID_BOOKING', 'Completed and paid, but never settled'), ('SETTLEMENT_WITHOUT_PAYMENT', 'Settled, but no successful payment'), ('SETTLEMENT_AMOUNT_MISMATCH', 'Settled for an amount the booking does not agree with'), ('SETTLEMENT_ON_UNFINISHED_BOOKING', 'Settled, but the booking is not completed'), ('STALE_SUBMITTED_PAYOUT', 'Transfer submitted long ago and still unresolved'), ('UNRESOLVED_PAYMENT', 'Payment pending far longer than any customer would wait')], max_length=40)),
                ('classification', models.CharField(choices=[('REPAIRED', 'Repaired automatically'), ('RETRYABLE', 'Will resolve itself on a later run'), ('REVIEW', 'Needs a person')], max_length=12)),
                ('subject_type', models.CharField(max_length=40)),
                ('subject_id', models.UUIDField()),
                ('subject_reference', models.CharField(blank=True, max_length=40)),
                ('detail', models.CharField(max_length=500)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'financial anomalies',
                'db_table': 'payments_financial_anomaly',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='gateway_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='gateway_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='transfer_provider',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payoutrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('transfer_reference', ''), _negated=True), fields=('transfer_reference',), name='payments_payout_unique_transfer_reference'),
        ),
        migrations.AddConstraint(
            model_name='payoutrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('submitted_at__isnull', True), ('transfer_reference', '')), models.Q(models.Q(('transfer_reference', ''), _negated=True), ('submitted_at__isnull', False)), _connector='OR'), name='payments_payout_submitted_at_matches_reference'),
        ),
        migrations.AddIndex(
            model_name='financialanomaly',
            index=models.Index(fields=['classification', '-last_seen_at'], name='payments_fi_classif_0a8a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='financialanomaly',
            index=models.Index(fields=['kind', '-last_seen_at'], name='payments_fi_kind_fb6f64_idx'),
        ),
        migrations.AddIndex(
            model_name='financialanomaly',
            index=models.Index(fields=['resolved_at'], name='payments_fi_resolve_950b4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialanomaly',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('kind', 'subject_id'), name='payments_anomaly_one_open_per_subject'),
        ),
    ]
